INSERT INTO exercises (id, category_id, type, prompt, correct_sign_id) VALUES
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra B?', (SELECT id FROM signs WHERE name='B')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra C?', (SELECT id FROM signs WHERE name='C')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra D?', (SELECT id FROM signs WHERE name='D')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿A qué letra corresponde este signo?', (SELECT id FROM signs WHERE name='E')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿A qué letra corresponde este signo?', (SELECT id FROM signs WHERE name='F')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra G?', (SELECT id FROM signs WHERE name='G')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra H?', (SELECT id FROM signs WHERE name='H')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra I?', (SELECT id FROM signs WHERE name='I')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿A qué letra corresponde este signo?', (SELECT id FROM signs WHERE name='J')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿A qué letra corresponde este signo?', (SELECT id FROM signs WHERE name='K')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra L?', (SELECT id FROM signs WHERE name='L')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra M?', (SELECT id FROM signs WHERE name='M')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿A qué letra corresponde este signo?', (SELECT id FROM signs WHERE name='N')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿A qué letra corresponde este signo?', (SELECT id FROM signs WHERE name='O')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra P?', (SELECT id FROM signs WHERE name='P')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra Q?', (SELECT id FROM signs WHERE name='Q')),
    (gen_random_uuid(), (SELECT id FROM categories WHERE name='Abecedario'), 'multiple_choice', '¿Cuál es el signo para la letra R?', (SELECT id FROM signs WHERE name='R'));