INSERT INTO "signs" ("id", "name", "category_id", "image_url", "video_url") VALUES
    (gen_random_uuid(), 'Antro', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Banco', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Calle', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Cantina', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Casa', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Centro', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Cine', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Ciudad', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Edificio', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),
    (gen_random_uuid(), 'Escuela', (SELECT id FROM categories WHERE name='Lugares'), NULL, NULL),